name: cypress-test
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress.io
        uses: cypress-io/github-action@v2
        with:
          start: npm start
# on: [push]
# jobs: 
#   run-cypress: 
#     runs-on: ubuntu-20.04 
#     steps: 
#       - name: checkout
#         uses: actions/checkout@v2
#       - name: cypress run
#         uses: cypress-io/github-action@v2
#         with:
#           project: ./